package com.biapay.core.model;

public enum TransactionType {
  MERCHANT_PAYMENT,
  PAYLINK_REQUEST,
  MONEY_TRANSFER,
  BILLING,
  MONEY_EXCHANGE,
  INVOICE_PAYMENT,
  BILL_PAYMENT,
  AIR_TIME,
  LOYALTY,
  REFERRAL,
  REFUND,
  CHARGEBACK,
  EVENT_PAYMENT,
  IN_STORE_PAYMENT,
  PAYOUT
}
