package com.biapay.core.constant;

public enum MessageType {
  SETTLEMENT_REQUEST,
  EMAIL_NOTIFICATION,
  SMS_NOTIFICATION,
  PAYLINK_CREATION,
  ACCOUNT_CREATION_REQUEST,
  ACCOUNT_TRANSACTION_REQUEST,
  SETTLE_HOLD_AMOUNT_REQUEST,
  ACCOUNT_SETTLEMENT_TRANSACTION_REQUEST,
  ACCOUNT_SETTLEMENT_DISBURSEMENT_TRANSACTION_REQUEST,
  ACCOUNT_DEBIT_REQUEST,
  ACCOUNT_CREDIT_REQUEST,
  WHATSAPP_NOTIFICATION;

}
