package com.biapay.core.constant.enums;

public enum KycApprovalStatus {
  PENDING_KYC_SUBMISSION,
  PENDING_FIRST_APPROVAL,
  PENDING_SECOND_APPROVAL,
  KYC_REJECTED,
  KYC_APPROVED,
  PENDING_KYC_VERIFICATION,
  PENDING_CONTRACT_VERIFICATION;
}
