package com.biapay.core.model.enums;

public enum SettlementStatus {
  APPROVED,
  REJECTED,
  PENDING_FOR_FIRST_APPROVAL,
  FIRST_APPROVED,
  PENDING_FOR_SECOND_APPROVAL,
  SECOND_APPROVED,
  AUTO_APPROVED,
  PENDING,
  COMPLETED,
  COMPLETED_ON_HOLD,
  IN_PROGRESS,
  FAILED,
  REVERSED,
  PENDING_CONFIRMATION
}
